### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by yusukebe** [yusukebe/ramen-api#1]
- [x] ~versioning API~
- [x] show powered by credit
- [x] GraphQL, Pagination
- [x] exports encode/decode base64 in Hono
- [x] pretty
- [x] Write API spec
- [x] ~Documentation in Japanese~
- [x] Documentation in English
- [x] ~Logo images?~
- [x] Add shops
- [x] `/shop/:id` return 404
- [x] ci
- [x] CD
- [x] LICENSE
- [x] Validate content
- [x] Add `uploaded by` or `author` user information?
- [x] ~linter~ and prettier
- [x] `photo > name`  => `photo => name , url`
- [x] ~~Pager in REST API~~
- [x] ~~Rate limit~~
- [x] ~random Endpoint?~
- [x] ~pager in REST API~
- [x] `/authors/{author_id}` endpoint
- [x] ~trail slash~
- [x] CORS
- [x] Example application <https://github.com/yusukebe/ramen-api-example>
- [x] Photo width/height?
- [x] ~resizer~
- [x] ~tags~
- [x] ~cache response~
- [x] ~address property for shops?~
- [x] limitation `/shops`
